HW2
DimonKhutornoy/afina pull request #2
Opened 2020-09-30 12:05 UTC by DimonKhutornoy

2020-10-01 14:33 UTC, xphoenix requested changes
+ разобраться где у тебя какие потоки

2020-10-01 14:33 UTC, xphoenix commented on src/network/mt_blocking/ServerImpl.cpp
> +    while (_worker.load()) {
```while (!_client_sockets.empty())```

2020-10-01 14:33 UTC, xphoenix commented on src/network/mt_blocking/ServerImpl.cpp
> +    _client_sockets.erase(client_socket);
race_condition

2020-10-01 14:33 UTC, xphoenix commented on src/network/mt_blocking/ServerImpl.cpp
> +
race condition

2020-10-03 17:07 UTC, Fen99 requested changes

2020-10-03 17:07 UTC, Fen99 commented on src/network/mt_blocking/ServerImpl.cpp
> +
Мьютекс, в этот момент сервер может добавлять в массив новый сокет. Тогда он не закроется на чтение

2020-10-03 17:07 UTC, Fen99 commented on src/network/mt_blocking/ServerImpl.cpp
>      close(_server_socket);
Join(), формально, может не быть вызван. Поэтому close нужно перенести в OnRun()

2020-10-03 17:07 UTC, Fen99 commented on src/network/mt_blocking/ServerImpl.cpp
> +            _cs_mutex.lock();
unique_lock на весь блок

2020-10-03 17:07 UTC, Fen99 commented on src/network/mt_blocking/ServerImpl.cpp
> +                _cs_mutex.lock();
К этому моменту std::thread нового воркера может уже завершиться, а ты только добавляешь сокет

2020-10-03 17:07 UTC, Fen99 commented on src/network/mt_blocking/ServerImpl.cpp
>      _logger->warn("Network stopped");
Сюда поместить close(server_socket)

2020-10-03 17:07 UTC, Fen99 commented on src/network/mt_blocking/ServerImpl.cpp
> +    std::size_t arg_remains;
= 0; //!!!

2020-10-03 17:07 UTC, Fen99 commented on src/network/mt_blocking/ServerImpl.cpp
> +        char client_buffer[4096];
= ""; //!!

2020-10-03 17:07 UTC, Fen99 commented on src/network/mt_blocking/ServerImpl.cpp
> +    _cs_mutex.unlock();
unique_lock

2020-10-03 17:42 UTC, Fen99 commented on src/network/mt_blocking/ServerImpl.cpp
> +    while (!_client_sockets.empty()){
Зачем здесь цикл?

2020-10-03 21:19 UTC, Fen99 approved these changes

2020-10-12 03:00 UTC, merged